name: Pint

on:
  push:
    branches:
      - develop
      - main
      - migration/full-blade
  pull_request:

jobs:
  pint:
    name: Check code style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: dom, fileinfo, mbstring
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run Pint
        run: ./vendor/bin/pint --test
